on:
  workflow_dispatch:
    inputs:
      release: 
        description: "Release name. String"
        default: "atlas-osb beta"  #TODO autogen mb?
        required: true
      version: #(major: -M, minor: -m, patch: -p)
        description: "Version key(-Mmp).Major.minor.patch,e.g. -M/-m/-p/-mp/etc"
        default: "-p"
        required: true
      draft:
        description: "Draft (release only). Boolean"
        default: "true"
        required: true
      postfix:
        description: "Add Posfix"
        required: false

jobs:
  test-increment-semver-job:
    runs-on: ubuntu-latest
    name: A job to test incrementing the version of a repository
    steps:

#      Note Checkout is required for ${GITHUB_WORKSPACE} to be not empty
      - name: Checkout
        uses: actions/checkout@v1

      - name: Increment Step Patch
        id: semver
        uses: leo-ri/increment-semver@master
        with:
          vlevel: ${{ github.event.inputs.version }}
          postfix: ${{ github.event.inputs.postfix }}